version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - echo $KUBE_CONFIG > ~/.kube/config
        - kubectl config set-context aws --namespace ff-remove-new;
        - echo "$(sed 's/!!!NAMESPACE!!!/'"ff-remove-new"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml

destroy:
  steps:
    setupVariables:
      after: *login-k8s
